#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# docker images
# docker run predict_stocks ./mlmodel/up_model.py
# python ./mlmodel/up_model.py
# python manage.py migrate --noinput
# python manage.py runserver 0.0.0.0:8001